# Generated by Django 4.2.4 on 2023-09-02 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('ayantdroit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DdeBpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socaff', models.CharField(max_length=100, verbose_name='Société')),
                ('centre', models.CharField(max_length=30, verbose_name='Centre')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('flaydrt', models.BooleanField(default=False, verbose_name='Ayant Droit ?')),
                ('relation', models.CharField(choices=[('moi meme', 'moi meme'), ('mon épouse', 'mon épouse'), ('mon époux', 'mon époux'), ('ma fille', 'ma fille'), ('mon fils', 'mon fils')], max_length=20, null=True, verbose_name="Filiation avec l'employé")),
                ('status', models.CharField(choices=[('crée', 'crée'), ('modifié', 'modifié'), ('supprimé', 'supprimé'), ('validé', 'validé')], max_length=20, null=True, verbose_name='Statut')),
                ('datcreat', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créer le')),
                ('ayantdroit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayantdroit.ayantdroit', verbose_name='Nom Ayant Droit')),
                ('nomcreat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créer Par')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel', verbose_name='Employé')),
            ],
        ),
    ]
