# Generated by Django 4.2.4 on 2023-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric', models.CharField(max_length=6, verbose_name='Matricule')),
                ('nompers', models.CharField(max_length=50, verbose_name="Nom de l'employé")),
                ('prenom', models.CharField(max_length=50, verbose_name="Prénom de l'employé")),
                ('sexe', models.CharField(max_length=10, verbose_name='Sexe')),
                ('datnais', models.CharField(max_length=20, null=True, verbose_name='Date Naiss')),
                ('sitfam', models.CharField(max_length=20, null=True, verbose_name='Sit. Fam')),
                ('nbrenf', models.CharField(max_length=10, null=True, verbose_name='Nbre Enf')),
                ('datcreat', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créer le')),
            ],
        ),
    ]
