# Generated by Django 4.2.4 on 2023-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='nompers',
            field=models.CharField(max_length=50, null=True, verbose_name="Nom de l'employé"),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(max_length=50, null=True, verbose_name="Prénom de l'employé"),
        ),
    ]
