# Generated by Django 4.2.4 on 2023-09-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0002_alter_personnel_nompers_alter_personnel_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='datmodif',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créer le'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='nomcreat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Par'),
        ),
    ]
