# Generated by Django 4.2.4 on 2023-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_datmodif_personnel_nomcreat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='datcreat',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='datmodif',
            field=models.CharField(max_length=20, null=True, verbose_name='Modifié le'),
        ),
    ]
