# Generated by Django 4.2.4 on 2023-09-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_personnel_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='matric',
            field=models.CharField(max_length=6, unique=True, verbose_name='Matricule'),
        ),
    ]
