# Generated by Django 4.2.4 on 2023-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyantDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matfil', models.CharField(max_length=9, verbose_name='Matricule')),
                ('nomayd', models.CharField(max_length=100, verbose_name='Nom Ayant Droit')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom Ayant Droit')),
                ('sexe', models.CharField(max_length=10, verbose_name='Sexe')),
                ('datnais', models.CharField(max_length=20, null=True, verbose_name='Date Naiss.')),
                ('filiation', models.CharField(max_length=20, null=True, verbose_name='Filiation')),
                ('datcreat', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créer le')),
            ],
        ),
    ]
