# Generated by Django 4.2.4 on 2023-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayantdroit', '0003_ayantdroit_datmodif_ayantdroit_nomcreat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayantdroit',
            name='datmodif',
            field=models.CharField(max_length=20, null=True, verbose_name='Modifie le'),
        ),
    ]
