# Generated by Django 4.2.4 on 2023-09-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayantdroit', '0005_ayantdroit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayantdroit',
            name='matfil',
            field=models.CharField(max_length=9, unique=True, verbose_name='Matricule'),
        ),
    ]
