# Generated by Django 4.2.4 on 2023-09-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric', models.CharField(max_length=6, verbose_name='Matricule')),
                ('nompers', models.CharField(max_length=50, verbose_name="Nom de l'employé")),
                ('prenom', models.CharField(max_length=50, verbose_name="Prenom de l'employé")),
                ('centre', models.CharField(max_length=30, null=True, verbose_name='Centre')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('actif', 'actif'), ('suspendu', 'suspendu'), ('licencié', 'licencié')], max_length=20, null=True, verbose_name='Statut')),
                ('datcreat', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créer le')),
                ('datmodif', models.CharField(max_length=20, null=True, verbose_name='Modifié le')),
                ('nomcreat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Par')),
            ],
        ),
    ]
