# Generated by Django 4.2.4 on 2023-09-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matric',
            field=models.CharField(max_length=6, unique=True, verbose_name='Matricule'),
        ),
    ]
